### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by LeloKarma** [viveksingh10/Electricity-Billing-System#18]
Hello please how do I get to contact you!?

**Comment by viveksingh10** [comment]
Bro, the project was create for a college assignment. 4 years back
The admin panel "admin", "admin" was the login username and pass and i didn't continued in the same tech stack

**Comment by LeloKarma** [comment]
Okay thank you 🙏

**Comment by viveksingh10** [comment]
check this file, https://github.com/viveksingh10/Electricity-Billing-System/blob/master/src/main/java/DB/checkLoginDAO.java
you need to create the admin table first then you can access it
